import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DrawerBar from './components/DrawerBar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aviel Aldama Diaz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <DrawerBar></DrawerBar>
      {children}        
      </body>

    </html>
  );
}
